/*
    SQL В ПРИМЕРАХ И ЗАДАЧАХ.
    ISBN 985-475-004-3
    Exercises from page 135
*/

-- 1
CREATE USER Petrov WITHOUT LOGIN;
GRANT UPDATE ON EXAM_MARKS TO Petrov

-- 2
CREATE USER Sidorov WITHOUT LOGIN;
GRANT SELECT ON EXAM_MARKS TO Sidorov WITH GRANT OPTION;
 
-- 3
CREATE USER Ivanov WITHOUT LOGIN;
REVOKE INSERT ON STUDENT FROM IVANOV;

-- 4
CREATE VIEW FOR_SIDOROV AS
    SELECT *
    FROM UNIVERSITY
    WHERE rating BETWEEN 300 AND 400
    WITH CHECK OPTION;

GRANT INSERT, UPDATE ON FOR_SIDOROV TO Sidorov;

-- 5 
CREATE VIEW FOR_PETROV AS
    SELECT *
    FROM EXAM_MARKS
    WHERE 2 =
        (SELECT MIN(mark)
        FROM EXAM_MARKS);

GRANT SELECT ON FOR_PETROV TO Petrov;